# Generated by Django 3.1.2 on 2020-10-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchroom',
            name='current_video',
            field=models.URLField(null=True),
        ),
    ]
