# Generated by Django 3.1.2 on 2020-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0002_watchroom_watchroomwatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchroomwatcher',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
