version: "3.8"

services:
  db:
    image: postgres:alpine
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: watchdog-vol
        target: /var/lib/postgresql/data
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: watchdog-vol
        target: /var/lib/postgresql/data

volumes:
  watchdog-vol:
