version: "3.8"

services:
  db:
    image: postgres:alpine
    env_file: ./.env
    expose:
      - "5432"
    volumes:
      - type: volume
        source: watchdog-vol
        target: /var/lib/postgresql/data
  cache:
    image: redis:alpine
    expose:
      - "6379"
  be_wsgi:
    build: ./watchdog_be
    depends_on:
      - db
      - cache
    expose:
      - "8000"
  be_asgi:
    build: ./watchdog_be
    command: ["daphne", "-b", "0.0.0.0", "-p", "8001", "watchdog_be.asgi"]
    depends_on:
      - db
      - cache
    expose:
      - "8001"
  fe:
    build: ./watchdog_fe
    depends_on:
      - be_wsgi
      - be_asgi
    ports:
      - "80:80"

volumes:
  watchdog-vol:
